### ISSUE TITLE
Plugin fetch all Specs on the local machine

### ISSUE THREAD

**Issue by KaiJSchaefer** [jfrog/cocoapods-art#13]
Hi, if i use the remote cocoa pods repo, the plugin will save all cocoa pods specs on my local machine (~756 MB). In my podfile i define only one dependency (Alamofire). I expected only the spec for Alamofire on my local machine.  Artifactory runs on a remote system.
I follow your instructions in the Screencast Sample and doesn`t finde the mistake.

**Comment by 85danf** [comment]
Cocoapods relies on the existence of the entire index locally, it does not query the remote for specific packages like soem other package managers do - the same behavior can be observed if you just ```cocoapods init``` or try to resolve dependencies when there is nothing under ```.cocoapods/repos``` - what the client does by default is a ```git clone``` of the entire specs repo (https://github.com/CocoaPods/Specs), resulting in the same amount of files (and size)
