### ISSUE TITLE
Issue with pod repo-art ...

### ISSUE THREAD

**Issue by ghost** [jfrog/cocoapods-art#2]
Hi,

I have trouble with add repository. The command is:
pod repo-art add dev http://...

Response:
[!] Unknown command: `repo-art`
Did you mean: repo?

My Setup:
Successfully installed cocoapods-art-0.9.4
Parsing documentation for cocoapods-art-0.9.4

pod --version
1.0.0

I also tried 'pod plugins' but I did not see cocoapods-art on available cocoaPods plugins.

**Comment by 85danf** [comment]
Hi,
The artifactory plugin is not currently listed under `pod plugins` in any case.
Can you paste the output of `gem list` ?

**Comment by ghost** [comment]
Yes, sure. 

Console output:
$ gem list

**\* LOCAL GEMS ***

activesupport (4.2.5)
addressable (2.3.8)
aws-sdk (1.66.0)
aws-sdk-v1 (1.66.0)
babosa (1.0.2)
bigdecimal (default: 1.2.0)
bundler (1.12.5, 1.11.1)
cert (1.4.1)
certified (1.0.0)
CFPropertyList (2.2.8)
claide (1.0.0, 1.0.0.beta.3, 0.9.1)
clamp (0.6.5)
cocoapods (1.0.0, 1.0.0.beta.6, 0.39.0)
cocoapods-art (0.9.4)
cocoapods-core (1.0.0, 1.0.0.beta.6, 0.39.0)
cocoapods-deintegrate (1.0.0, 1.0.0.beta.1)
cocoapods-downloader (1.0.0, 1.0.0.beta.2, 0.9.3)
cocoapods-plugins (1.0.0, 1.0.0.beta.1, 0.4.2)
cocoapods-search (1.0.0, 1.0.0.beta.1, 0.1.0)
cocoapods-stats (1.0.0, 1.0.0.beta.3, 0.6.2)
cocoapods-trunk (1.0.0, 1.0.0.beta.2, 0.6.4)
cocoapods-try (1.0.0, 1.0.0.beta.3, 0.5.1)
colored (1.2)
commander (4.3.5)
credentials_manager (0.16.0)
cupertino (1.3.4)
deliver (1.13.1, 1.11.3)
domain_name (0.5.25)
dotenv (2.0.2)
dubai (0.1.0)
escape (0.0.4)
excon (0.45.4)
faraday (0.9.2, 0.8.11)
faraday-cookie_jar (0.0.6)
faraday_middleware (0.10.0)
fastimage (1.6.8)
fastlane (1.95.0, 1.91.0, 1.90.0, 1.89.0)
fastlane_core (0.46.3, 0.45.0, 0.44.1, 0.43.5)
fourflusher (0.3.0)
frameit (2.7.0, 2.6.2)
fuzzy_match (2.0.4)
google-api-client (0.9.6)
googleauth (0.5.1)
gym (1.6.3)
highline (1.7.8)
houston (2.2.3)
http-cookie (1.0.2)
httpclient (2.8.0)
hurley (0.2)
i18n (0.7.0)
io-console (default: 0.4.2)
jazzy (0.5.0)
json (1.8.3, default: 1.7.7)
jwt (1.5.4)
krausefx-shenzhen (0.14.7)
libxml-ruby (2.6.0)
liferaft (0.0.4)
little-plugger (1.1.4)
logging (2.1.0)
match (0.6.0)
mechanize (2.5.1)
memoist (0.14.0)
mime-types (1.25.1)
mime-types-data (3.2016.0521)
mini_magick (4.5.1)
mini_portile2 (2.0.0)
minitest (5.8.3, default: 4.3.2)
molinillo (0.4.5, 0.4.4, 0.4.0)
multi_json (1.12.1)
multi_xml (0.5.5)
multipart-post (2.0.0, 1.2.0)
mustache (0.99.8)
nap (1.0.0)
net-http-digest_auth (1.4)
net-http-persistent (2.9.4)
net-sftp (2.1.2)
net-ssh (3.0.1)
netrc (0.7.8)
nokogiri (1.6.7, 1.5.6)
nomad-cli (0.0.2)
ntlm-http (0.1.1)
open4 (1.3.4)
os (0.9.6)
pem (1.3.1)
pilot (1.9.2, 1.7.0, 1.6.0)
plist (3.1.0)
produce (1.1.2)
psych (default: 2.0.0)
rack (1.6.4)
rack-protection (1.5.3)
rake (default: 0.9.6)
rdoc (default: 4.0.0)
redcarpet (3.3.4)
representable (2.3.0)
retriable (2.1.0)
rouge (1.10.1)
rubygems-update (2.6.4)
rubyzip (1.1.7)
sass (3.4.21)
scan (0.8.0, 0.7.1, 0.7.0, 0.6.1)
screengrab (0.3.2)
security (0.1.3)
sentry-raven (0.15.6)
shenzhen (0.14.2)
showterm (0.5.0)
sigh (1.8.0)
signet (0.7.2)
sinatra (1.4.6)
slack-notifier (1.5.1)
slather (1.8.2)
snapshot (1.12.3, 1.12.2)
spaceship (0.27.2, 0.27.1)
sqlite3 (1.3.7)
supply (0.7.0)
term-ansicolor (1.0.7)
terminal-notifier (1.6.3)
terminal-table (1.4.5)
test-unit (default: 2.0.0.0)
thor (0.19.1)
thread_safe (0.3.5)
tilt (2.0.1)
tzinfo (1.2.2)
uber (0.0.15)
unf (0.1.4)
unf_ext (0.0.7.1)
venice (0.2.0)
webrobots (0.1.1)
word_wrap (1.0.0)
xcinvoke (0.2.0)
xcode-install (1.4.0)
xcodeproj (1.0.0, 1.0.0.beta.3, 0.28.2, 0.27.2)
xcpretty (0.2.2, 0.2.1)
xcpretty-travis-formatter (0.0.4)

**Comment by 85danf** [comment]
`cocoapods (1.0.0, 1.0.0.beta.6, 0.39.0)
cocoapods-art (0.9.4)
cocoapods-core (1.0.0, 1.0.0.beta.6, 0.39.0)
cocoapods-deintegrate (1.0.0, 1.0.0.beta.1)
cocoapods-downloader (1.0.0, 1.0.0.beta.2, 0.9.3)
cocoapods-plugins (1.0.0, 1.0.0.beta.1, 0.4.2)
cocoapods-search (1.0.0, 1.0.0.beta.1, 0.1.0)
cocoapods-stats (1.0.0, 1.0.0.beta.3, 0.6.2)
cocoapods-trunk (1.0.0, 1.0.0.beta.2, 0.6.4)
cocoapods-try (1.0.0, 1.0.0.beta.3, 0.5.1)`

You have multiple versions of CocoaPods installed - this is a surefire way to have issued such as the one you're reporting.. I suggest you `gem uninstall` all versions of CocoaPods and install just v 1.0

You should remove cocoapods-art first and `gem install` it only after installing cocoapods

**Comment by 85danf** [comment]
BTW, we're on the plugin list now as well you'll see it next time you run `pod plugins`

**Comment by ghost** [comment]
The tip with `gem uninstall` all versions od Cocoapods works. I can work with repo-art now. @feldan thank you for your help.
