### ISSUE TITLE
Possibility of specifying path to .netrc file

### ISSUE THREAD

**Issue by lursk** [jfrog/cocoapods-art#22]
Hi, we've met a problem with injecting credentials on our CI. The static .netrc file in home directory is a bit problematic, because there's a problem with managing it on every build agent (we have a lot of projects and its number is changing with time and so credentials), the other problem is managing access to it. If some developer in my company is involved in one project, I don't want him to have access to all credentials. It would be a good idea to give an option of setting path to .netrc file. So it would be possible to manage credentials with master CI server or even to have separate files attached to each project.

I've already prepared PR (#21) with my solution. Could you review it?

**Comment by eyalbe4** [comment]
@lursk 👍 
The PR looks good - thanks!
I think we can close this issue.
