### ISSUE TITLE
pod install failed when Podfile.lock exists

### ISSUE THREAD

**Issue by SomnusLee1988** [jfrog/cocoapods-art#25]
We are using jFrog artifactory repo and setup the cocoapod_local repo on artifactory. The pod install failed with error 
Pod::StandardError - [BUG] Failed to find known source with the URL "http://xxxx/artifactory/api/pods/xxxx"

ps. CocoaPods version 1.6.1

**Comment by lursk** [comment]
As a workaround I can temporally recommend to switch to the older CocoaPods version, which is 1.5.3. I'll look into the problem at the weekend.

**Comment by SomnusLee1988** [comment]
I have found a workaround for this bug.
https://github.com/jfrog/cocoapods-art/pull/26

**Comment by SomnusLee1988** [comment]
please close this issue, cause #26 has been merged @lursk
