### ISSUE TITLE
Path repos_path/cocoapods-local already exists - remove it first

### ISSUE THREAD

**Issue by seanliu1** [jfrog/cocoapods-art#31]
`pod repo-art add cocoapods-local "https://xxxxx/api/pods/cocoapods-local"

`Retrieving index from `https://xxxxx/api/pods/cocoapods-local` into local spec repo `cocoapods-local`
[!] Path repos_path/cocoapods-local already exists - remove it first, or run 'pod repo-art update cocoapods-local' to update it

`pod repo-art remove cocoapods-local
`[!] repo cocoapods-local does not exist

I also removed the entire cocoapods-local folder locally, but I still see this issue, when I try to add

**Comment by Apanlin** [comment]
I also met the same problem. How did you solve it

**Comment by nlasso** [comment]
just for anyone that get's into this issue as well. I was able to fix it by going to `cd ~/.cocoapods/repos` and `cd ~/.cocoapods/repos-art` and removing the repo that has the error from both directories. It seems that the `remove` command is not deleting it from both.
