### ISSUE TITLE
pod install changing source to master Specs repo when upgrading CocoaPods to 1.7.5

### ISSUE THREAD

**Issue by rwalbergpd** [jfrog/cocoapods-art#34]
I have been using CocoaPods successfully with Artifactory for over a year with CocoaPods 1.5.3.

Today I updated to 1.7.5 and did a `$ pod install`, and I started getting this:

```
rwalberg@Ryans-MacBook-Pro:iOS (pod-bump-2019-aug)$ bundle exec pod install
/Users/rwalberg/.cocoapods/repos-art/cocoapods-remote/.artpodrc
Analyzing dependencies
/Users/rwalberg/.cocoapods/repos-art/cocoapods-remote/.artpodrc
/Users/rwalberg/.cocoapods/repos-art/cocoapods-remote/.artpodrc
Downloading dependencies
Installing ALAlertBanner 0.3.1 (source changed to `https://github.com/CocoaPods/Specs.git` from `https://pagerduty.jfrog.io/pagerduty/api/pods/cocoapods-remote`)
^C[!] Cancelled
```

This isn't right, since the `Podfile.lock` says they come from Artifactory.

Nothing has changed in my Podfile. It still says this:

```
plugin 'cocoapods-art', :sources => [
  'cocoapods-remote'
]
```

Is CocoaPods 1.7.5 not supported by the cocoapods-art gem?

**Comment by HenriBeck** [comment]
@rwalbergpd 

I think I had the same issue. For me, all of the downloads which referenced the master repo broke after adding the `cocoapods-art` plugin.

I fixed this by adding the following line after the `plugin 'cocoapods-art'` definition
```
source 'https://github.com/CocoaPods/Specs.git'
```

**Comment by rwalbergpd** [comment]
Thanks @henribeck but that’s a different problem. None of my pods are supposed to reference the master repo, and after I do a pod install, they all do.

**Comment by westrada** [comment]
Hi @rwalbergpd I had the same issue and I resolved it updating the cocoapods and cocoapods-art versions. Those are the versions I'm using now without that issue
```
cocoapods -> 1.8.3
cocoapods-art -> 1.0.4
```

**Comment by ashokds** [comment]
Hi @rwalbergpd , were you able to resolve this issue? I am also getting similar output and `podfile.lock` has diffs.

#42 

Using `cocoapods-art-1.0.2.gem` with `cocoapods-1.9.1`

**Comment by rwalbergpd** [comment]
@ashokds I am using `cocoapods-art-1.0.4` with `cocoapods-1.8.4` and it's working.
