### ISSUE TITLE
Plugin is incompatible with http headers option

### ISSUE THREAD

**Issue by jasonschroeder-sfdc** [jfrog/cocoapods-art#43]
https://github.com/jfrog/cocoapods-art/blob/master/lib/cocoapods_plugin.rb is overriding `Pod::Downloader::Http`, and the contents of this PR are not in the artifactory version. https://github.com/CocoaPods/cocoapods-downloader/pull/89

We have private, published podspecs that use the 'header' key, but when the artifactory plugin is installed, cocoapods crashes.

I see a few options:

1. copy/paste the changes from https://github.com/CocoaPods/cocoapods-downloader/pull/89 into https://github.com/jfrog/cocoapods-art/blob/master/lib/cocoapods_plugin.rb
2. Open a PR against https://github.com/CocoaPods/cocoapods-downloader, ask for an extension point to add parameters to `curl`, get it merged, and then refactor cocoapods-art to use that extension point

**Comment by eyalbe4** [comment]
Thank you for reporting this issue @jasonschroeder-sfdc!
We'll be looking into this issue and provide an update here.
