### ISSUE TITLE
"pod repo-art add" leads to error

### ISSUE THREAD

**Issue by choli** [jfrog/cocoapods-art#7]
We are trying to add Artifactory with cocoapods to our toolchain. Now I have followed all steps (create a remote repository for pods on our artifactory instance and installed cocoapods-art) to be ready to add the repo. But then this command leads to different errors:
`pod repo-art add artMaster "http://ourUrl:port/artifactory/api/pods/cocoapods-master"`
- First I had a 401 error. Then we opened the remote repository to anonymous
- This gives now a 404 error. `(22) The requested URL returned error: 404`
- Another option was trying with any public artifactory to test, so I tried the following: `pod repo-art add beanstream-public "https://beanstream.artifactoryonline.com/beanstream/api/pods/beanstream-public"` and that worked perfectly

So I guess there is something I missed or messed up while setting up the remote repository in artifactory. Can you lead me to the right path here?

Here is the full error message:

> `Retrieving index from 'http://ourUrl:port/artifactory/api/pods/cocoapods-master' into local spec repo 'artMaster'
> [!] Error getting the index from Artifactory at: 'http://ourUrl:port/artifactory/api/pods/cocoapods-master' : [!] /usr/bin/curl -n -f -L -o /Users/myUser/.cocoapods/repos/artMaster/Specs/file.tgz http://ourUrl:port/artifactory/api/pods/cocoapods-master/index/fetchIndex --create-dirs curl: (22) The requested URL returned error: 404`

**Comment by choli** [comment]
Can be closed. I guess it was because of the first try, that I haven't had the rights (caching problem?). Today when I created a new remote repository, it worked with the first try.

**Comment by gtrog** [comment]
I've had the same issue, the error can be misleading, but, ultimately for me it was giving me a 404 because the user I was adding the repo as didn't have write/cache access for the remote repository, which is required for remote repositories to be able to cache things.
